DROP TABLE PRODUCT IF EXISTS;
CREATE TABLE PRODUCT (
	ID BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	SKU VARCHAR(25) NOT NULL,
	NAME VARCHAR(25) NOT NULL,
	DESCRIPTION VARCHAR(50) ,
	constraint SKU_UN unique (SKU)
) ;

DROP TABLE USER IF EXISTS;
CREATE TABLE USER (
	ID BIGINT IDENTITY NOT NULL PRIMARY KEY ,
	EMAIL VARCHAR(25) NOT NULL,
	FIRST_NAME VARCHAR(25),
	LAST_NAME VARCHAR(25),
	constraint EMAIL_UN unique (EMAIL)
) ;